### ISSUE TITLE
How low level did you go to make the app?

### ISSUE THREAD

**Issue by Raj2032** [AlexxxRu/TinyPomodoro#2]
![image](https://user-images.githubusercontent.com/29293830/163708898-606ee350-2dda-44e6-9458-8002b4ef7fb6.png)

This looks quite amazing, I believe you guys used egui, am I correct?

Did you had to go low level to make custom UI as egui by default does not look like this?

**Comment by AlexxxRu** [comment]
Hello.
No, I don't use any low-level tricks for the UI side. I've used "low level" only for hotkeys and window control (focus/activate/hide/etc) things.

The hardest part here was SVG icons and progress circle. As I know, egui already implemented SVG loading, so it should be easier now. 

Sliders can be customized via [Style](https://docs.rs/egui/latest/egui/style/struct.Style.html) struct. 
Pseudocode workflow:
```
// Set desired color
 style.visuals.widgets.active.bg_fill = some color;
// Draw slider
Slider::new(value, range);

// Set another color
 style.visuals.widgets.active.bg_fill = some color;
// Draw
Slider::new(value, range);

// etc
```

The progress circle is just 2 circles with different line widths and colors.
Here is simple [example](https://github.com/AlexxxRu/TinyPomodoro/blob/main/app/src/app/widgets/progress_circle.rs). In short, you need to calculate [points](https://math.stackexchange.com/questions/260096/find-the-coordinates-of-a-point-on-a-circle) and draw them via [LineSegment](https://docs.rs/egui/latest/egui/enum.Shape.html#variant.LineSegment). 

Overall, I'm pretty impressed by this library, but it is still very far away from Qt and other GUI frameworks.

**Comment by Raj2032** [comment]
@AlexxxRu Its quite good mate, I want to make something similar, thanks for your help mate =D

> Overall, I'm pretty impressed by this library, but it is still very far away from Qt and other GUI frameworks.

To be honest I don't know how can egui can improve (other than having caching capabilities), it seems to do what it is supposed to do. In your opinion what is missing compared to Qt and other GUI frameworks?

Also what backend renderer are you using if I may ask?

**Comment by AlexxxRu** [comment]
> Isn't it possible to draw this through egui by drawing a custom shape or something?

Yes, I think it is possible. But I prefer to use some open source web icons. I'm too lazy to create or port icons by myself :)

> In your opinion what is missing compared to Qt and other GUI frameworks?

Some basic functionality, like show/hide/focus/etc window. The application doesn't have direct access to the `winit` struct. So I'm forced to fork it and forward the window to the application.

I'm hardly struggling without the Qt signals or JS events. F.e. I want to have a simple struct, which will upload the file and fire an event after each chunk is uploaded. So ANY other component or multiple components can catch it and update the application UI. 
But I'm very unsure, that it is possible to implement it idiomatic in Rust.

**Comment by AlexxxRu** [comment]
I'm using egui-glow

**Comment by Raj2032** [comment]
@AlexxxRu 

> Yes, I think it is possible. But I prefer to use some open source web icons. I'm too lazy to create or port icons by myself :)

Oh interesting I thought you created the icons yourself :)

> Some basic functionality, like show/hide/focus/etc window. The application doesn't have direct access to the winit struct. So I'm forced to fork it and forward the window to the application.

Ah right I see mate.

> I'm hardly struggling without the Qt signals or JS events. F.e. I want to have a simple struct, which will upload the file and fire an event after each chunk is uploaded. So ANY other component or multiple components can catch it and update the application UI.

Right I see mate.

> But I'm very unsure, that it is possible to implement it idiomatic in Rust.

I am pretty noob :)

> I'm using egui-glow

Oh nice mate :)

**Comment by Raj2032** [comment]
@AlexxxRu Sorry bro just question, if I were to draw my own shape, would it be a lot of difficulty or it should be easy?

**Comment by AlexxxRu** [comment]
You can use any of this predefined shape. Or draw own based on calculated points coordinates
https://docs.rs/egui/latest/egui/enum.Shape.html

**Comment by Raj2032** [comment]
@AlexxxRu Thanks mate :)
